apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mysql-service-instance-read-only
  namespace: default
spec:
  # References service name and plan name
  clusterServiceClassExternalName: rds-mysql
  clusterServicePlanExternalName: 5-7-read-only-replica
  # Additional parameters can be added here,
  # which may be used by the service broker.
  parameters:
    name: "replication"
    replica_of_id: "8867ae31b8944ff3ab3993ac08a01d68in01"
    availability_zone: "eu-west-0a"
