apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mysql-service-instance
  namespace: default
spec:
  # References service name and plan name
  clusterServiceClassExternalName: rds-mysql
  clusterServicePlanExternalName: 5-7-17
  # Additional parameters can be added here,
  # which may be used by the service broker.
  parameters:
    name: "RDSMysql"
    database_password: "Password1234!"
